// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyzdeszixwivealgidey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5emRlc3ppeHdpdmVhbGdpZGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDczNzMsImV4cCI6MjA2NjAyMzM3M30.qd0oNQkEpYFyvG0JJs4eu0YynYUPnwebuzhQDn96cdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);